- include_role:
    name: farynam.mfitbs_openvpn_easyrsa
  vars:
    importServerCertGen : true

- name: Create host pki dir
  file:
    path: "{{ host_pki_dir }}"
    state: directory
    mode: '0700'

- name: Copy Server cert to the machine
  copy:
    src: "{{ LOCAL_REPO }}/servers/issued/{{ server_host }}.crt"
    dest: "{{ host_pki_dir }}/."
    mode: 0600

- name: Copy Server key to the Server
  copy:
    src: "{{ LOCAL_REPO }}/servers/private/{{ server_host }}.key"
    dest: "{{ host_pki_dir }}/."
    mode: 0600

- name: Copy CA to the server
  copy:
    src: "{{ LOCAL_REPO }}/ca.crt"
    dest: "{{ host_pki_dir }}/"
    mode: 0600

- name:  Copy dh to remote
  copy:
    src: "{{ LOCAL_REPO }}/servers/dh_{{ server_host }}.pem"
    dest: "{{ host_pki_dir }}/"
    mode: 0600

- name:  Copy secret to remote
  copy:
    src: "{{ LOCAL_REPO }}/ta.key"
    dest: "{{ host_pki_dir }}/"
    mode: 0600

- name: Copy server template
  copy:
    src: "{{ LOCAL_REPO }}/servers/{{ server_host }}.conf"
    dest: "{{ OPEN_VPN_CFG }}/server.conf"
    mode: 0600

- name: Create ccd dir
  file:
    path: "{{ OPEN_VPN_CFG }}/ccd"
    state: directory
    mode: '0700'

- name: Enable Server
  command: systemctl enable openvpn@server.service

- name: Restart openvpn
  command: systemctl restart openvpn@server.service
